### ISSUE TITLE
任何视频弹幕都变成了重复的两行

### ISSUE THREAD

**Issue by wenjiazhou123** [xmcp/pakku.js#232] opened 2022-12-13 11:12 UTC
**是否可以稳定复现：**

是

**复现步骤：**

1. 任何视频弹幕都变成了重复的两行
2. 版本是
![image](https://user-images.githubusercontent.com/44669282/207302732-718ffae2-6f08-4317-b7ea-d9a662eb56c5.png)

![image](https://user-images.githubusercontent.com/44669282/207302231-0c50bf96-f08d-4126-9e1d-8f144988fb95.png)

**预期行为：**

任何视频弹幕都变成了重复的两行

**实际行为：**

任何视频弹幕都变成了重复的两行

**禁用pakku后bug是否存在：**

否

**禁用其他插件后bug是否存在：**

是

**B站播放器版本号：**

![image](https://user-images.githubusercontent.com/44669282/207302561-166ad3ca-f87a-4c00-bb9a-1a136696abf1.png)

**pakku调试信息：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.4

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"off","DANMU_MARK":"prefix","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1670910006321","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","THRESHOLD":"1","TRIM_WIDTH":"on","POPUP_BADGE":"percent","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","CLOUD_SYNC":"off","WHITELIST":"[]","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"60","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"157472826":{"identical":1,"edit_distance":1,"pinyin_distance":0,"cosine_distance":0,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":1,"total":274,"onscreen":272,"maxcombo":2,"maxdispval":44.57090682363856,"error":null,"cid":"898958431","parse_time_ms":29}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"1","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1670910006321"}

**Tabs:**

- ID=157472777 status=complete `undefined`

- ID=157472778 status=complete `undefined`

- ID=157472779 status=complete `undefined`

- ID=157472780 status=complete `undefined`

- ID=157472781 status=unloaded `undefined`

- ID=157472782 status=unloaded `undefined`

- ID=157472783 status=complete `undefined`

- ID=157472825 status=complete `https://www.bilibili.com/`

- ID=157472826 status=complete `https://www.bilibili.com/video/BV1ZD4y1s7kM/`

- ID=157472827 status=complete `undefined`

- ID=157472832 status=complete `undefined`

- ID=157472833 status=complete `undefined`

- ID=157472837 status=loading `undefined`

- ID=157472835 status=complete `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,11">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,11">Ocarina的声音好奇怪</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,1">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,1">]][[</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,11">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,11">Ocarina的声音好奇怪</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,1">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,1">]][[</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

我认为可能是edge新版本的问题

**Comment by lanmaoaiwo** [comment] 2022-12-13 12:56
我也这样

**Comment by HatsukiH** [comment] 2022-12-13 13:46
+1 同样问题

**Comment by xmcp** [comment] 2022-12-13 14:14
duplicate of #230

**Closed by xmcp** 2022-12-13 14:14 UTC
