### ISSUE TITLE
弹幕双倍出现

### ISSUE THREAD

**Issue by IzayoiSakuya-viewer** [xmcp/pakku.js#231] opened 2022-12-11 12:05 UTC
**是否可以稳定复现：**

可以，刷新网页、重启浏览器或路由器都没能解决，重装扩展也没用。

**复现步骤：**

1. 今天打开视频后突然发现的，不知道原因为何。
2. 特定视频：https://www.bilibili.com/bangumi/play/ss42186
3. 其他普通视频也试过了，似乎没有问题，但是其他番剧还没有测试过，不确定是否是通病。

**预期行为：**

？正常的行为（即弹幕正常显示）

**实际行为：**

弹幕突然显示为双倍了
图片：（虽然这张图中没有显示，但是后续我关了其他插件和扩展，依旧存在这个问题）
[https://i.postimg.cc/qvP5JXkV/QQ-20221211194242.png](url)

**禁用pakku后bug是否存在：**

不存在了

**禁用其他插件后bug是否存在：**

依旧存在

**B站播放器版本号：**

3.24.0-2fca4ff4

**pakku调试信息：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.4

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46`

**Incognito:** `false`

**localStorage:** `{"_ADVANCED_USER":"on","MARK_THRESHOLD":"10","TOOLTIP_KEYBINDING":"on","DANMU_MARK":"suffix","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1670759755758","SHRINK":"on","TRIM_SPACE":"on","MAX_DIST":"8","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","THRESHOLD":"40","TRIM_WIDTH":"on","POPUP_BADGE":"percent","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","WHITELIST":"[]","CLOUD_SYNC":"off","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","MAX_COSINE":"30","ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"20","AUTO_DISABLE_DANMU":"off","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"1519465283":{"identical":0,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":0,"scroll":0,"taolu":0,"total":9,"onscreen":9,"maxcombo":1,"maxdispval":9.000000000000002,"error":null,"cid":"900603173","parse_time_ms":1},"1519465292":{"identical":181,"edit_distance":2198,"pinyin_distance":35,"cosine_distance":105,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":125,"shrink":1788,"scroll":0,"taolu":1,"total":5729,"onscreen":3210,"maxcombo":126,"maxdispval":394.0859212476255,"error":null,"cid":"908758746","parse_time_ms":743}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"10","MAX_COSINE":"30","MAX_DIST":"8","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REPRESENTATIVE_PERCENT":"20","SCROLL_THRESHOLD":"1200","SHRINK":"on","THRESHOLD":"40","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1670759755758"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=1519465228 status=complete `undefined`

- ID=1519465232 status=complete `undefined`

- ID=1519465235 status=complete `undefined`

- ID=1519465238 status=complete `undefined`

- ID=1519465241 status=complete `undefined`

- ID=1519465244 status=complete `undefined`

- ID=1519465247 status=complete `undefined`

- ID=1519465250 status=complete `undefined`

- ID=1519465253 status=complete `undefined`

- ID=1519465256 status=complete `undefined`

- ID=1519465259 status=complete `undefined`

- ID=1519465262 status=complete `https://www.bilibili.com/video/av639026705/?vd_source=9ce6c84dca97712e7f11bab1d4962d6e`

- ID=1519465265 status=complete `https://www.bilibili.com/video/av689814741/?vd_source=9ce6c84dca97712e7f11bab1d4962d6e`

- ID=1519465268 status=unloaded `https://www.bilibili.com/video/av722181818/`

- ID=1519465271 status=unloaded `https://space.bilibili.com/84438004/article`

- ID=1519465274 status=unloaded `undefined`

- ID=1519465277 status=unloaded `undefined`

- ID=1519465280 status=unloaded `undefined`

- ID=1519465283 status=complete `https://www.bilibili.com/video/av520465202/?vd_source=9ce6c84dca97712e7f11bab1d4962d6e`

- ID=1519465286 status=complete `undefined`

- ID=1519465289 status=unloaded `https://search.bilibili.com/all?keyword=%E5%BE%B7%E5%87%AF&from_source=web_search`

- ID=1519465292 status=complete `https://www.bilibili.com/bangumi/play/ss42186/?from=search&seid=2852561778630229304&spm_id_from=333.337.0.0`

- ID=1519465295 status=complete `undefined`

- ID=1519465300 status=complete `undefined`

- ID=1519465307 status=complete `undefined`

- ID=1519465344 status=complete `undefined`

- ID=1519465310 status=complete `undefined`

- ID=1519465313 status=complete `undefined`

- ID=1519465357 status=complete `undefined`

- ID=1519465366 status=loading `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,11">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,11">Ocarina的声音好奇怪</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,1">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,1">]][[</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,11">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,11">Ocarina的声音好奇怪</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,1">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,1">]][[</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

打开视频一瞬间刷出来的弹幕都是单个的，但是随着进度条延伸新出现的弹幕就双倍了。

**Comment by IzayoiSakuya-viewer** [comment] 2022-12-11 12:07
[![QQ-20221211194242.png](https://i.postimg.cc/qvP5JXkV/QQ-20221211194242.png)](https://postimg.cc/mPSwV9z8)

**Comment by xmcp** [comment] 2022-12-11 13:44
这是已知问题，更新到10.2.5可以解决
duplicate of #230

**Closed by xmcp** 2022-12-11 13:44 UTC
