### ISSUE TITLE
使用360极速x浏览器的话，弹幕一直显示填充中不显示，只有关掉插件才能正常使用

### ISSUE THREAD

**Issue by moshangqian** [xmcp/pakku.js#256] opened 2023-09-16 07:02 UTC
**是否可以稳定复现：**

是

**复现步骤：**

1. 使用360极速x浏览器

**预期行为：**

视频和弹幕都正常播放

**实际行为：**

弹幕始终显示填充中，完全看不到弹幕。
![image](https://github.com/xmcp/pakku.js/assets/144510153/43bfa2ee-8a32-4786-a633-8689977a4c02)

**禁用pakku后bug是否存在：**

禁用后弹幕恢复正常。

**禁用其他插件后bug是否存在：**

禁用其他插件后bug依旧存在。

**B站播放器版本号：**

4.5.3-d13c37f3

**pakku调试信息：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.7

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"prefix","CLOUD_SYNC":"off","TOOLTIP_KEYBINDING":"on","BLACKLIST":"[]","_LAST_UPDATE_TIME":"0","_ADVANCED_USER":"off","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","THRESHOLD":"20","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"0"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=2 status=complete `https://www.bilibili.com/`

- ID=61 status=complete `https://www.bilibili.com/video/BV1sh4y1T7Ms/?spm_id_from=333.1007.tianma.2-2-5.click&vd_source=60f9b6e1626f023ebb53d8fff8e8574a`

- ID=63 status=complete `https://www.bilibili.com/`

- ID=64 status=loading `https://www.bilibili.com/video/BV1p14y1B7cj/?spm_id_from=333.788.recommend_more_video.1&vd_source=60f9b6e1626f023ebb53d8fff8e8574a`

- ID=65 status=loading `undefined`

- ID=66 status=loading `undefined`

- ID=67 status=unloaded `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

我是先找到了b站客服，然后b站客服推荐我关掉这个插件……我不知道这个有没有帮助。

**Comment by xmcp** [comment] 2023-09-16 07:06
Duplicate of #254

**Closed by xmcp** 2023-09-16 07:06 UTC
