### ISSUE TITLE
目前擴展失效 會導致網站無法加載彈幕

### ISSUE THREAD

**Issue by tkp206093** [xmcp/pakku.js#255] opened 2023-09-15 14:20 UTC
**是否可以稳定复现：**

是

**复现步骤：**

1. 開啟擴展
2. 開啟b站視頻

**预期行为：**

![image](https://github.com/xmcp/pakku.js/assets/29872453/1091c04b-dfd4-4027-9c97-f48c08d8a15c)

**实际行为：**

![image](https://github.com/xmcp/pakku.js/assets/29872453/db2ad357-dc75-4d23-86a2-ed1f2238ec39)

**禁用pakku后bug是否存在：**

否

**禁用其他插件后bug是否存在：**

是

**B站播放器版本号：**

4.5.3-rc.3113.0-ff9c75cb

**pakku调试信息：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.7

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.81`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"on","DANMU_MARK":"prefix","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1694787477076","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","THRESHOLD":"20","TRIM_WIDTH":"on","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","CLOUD_SYNC":"on","WHITELIST":"[]","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"60","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=1151970865 status=complete `undefined`

- ID=1151970981 status=complete `https://www.bilibili.com/video/BV1h841197as/`

- ID=1151970996 status=complete `undefined`

- ID=1151970992 status=complete `undefined`

- ID=1151971004 status=loading `undefined`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1694787477076"}

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

懷疑b站更改接口還是怎樣 擴展應用程式一直顯示彈幕下載中

**Comment by Yesinger** [comment] 2023-09-15 18:09
同

**Comment by theblueandblackcrow** [comment] 2023-09-15 18:35
引用，同一类问题#254

**Comment by xmcp** [comment] 2023-09-15 22:08
Duplicate of #254

**Closed by xmcp** 2023-09-15 22:08 UTC
