### ISSUE TITLE
[bug]关于页面内flash播放器无法查询弹幕信息的问题

### ISSUE THREAD

**Issue by aclihub** [xmcp/pakku.js#112] opened 2019-10-02 05:49 UTC
又是我，问题如下图
![bug2](https://user-images.githubusercontent.com/54567707/66020908-55ed3f00-e51b-11e9-878d-b57e7981addc.png)
又是这个链接，又是这个视频
https://www.bilibili.com/blackboard/topic/Railgun_10years_web.html
![09edef7cd0dd765e0a45faca502848cc375037b0 jpg@880w_440h](https://user-images.githubusercontent.com/54567707/66020954-7917ee80-e51b-11e9-94d9-9c4f3512d3c9.jpg)

**Comment by xmcp** [comment] 2019-10-02 12:21
duplicate of #111

**Closed by xmcp** 2019-10-02 12:21 UTC
