### ISSUE TITLE
插件:"本页面没有发现B站播放器"

### ISSUE THREAD

**Issue by sanxi-cn** [xmcp/pakku.js#251] opened 2023-08-21 16:51 UTC
重启电脑后edge浏览器的插件就会显示"本页面没有发现B站播放器",相同插件环境下的谷歌浏览器就没这个问题

**是否可以稳定复现：**

是的

**复现步骤：**

1. 电脑重启后就这样了

**预期行为：**

**实际行为：**

![image](https://github.com/xmcp/pakku.js/assets/142826155/79b15333-90d2-4344-afa8-97415e19cd91)

**禁用pakku后bug是否存在：**

**禁用其他插件后bug是否存在：**

存在

**B站播放器版本号：**

4.4.1-200c3fd1

**pakku调试信息：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.6

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"off","DANMU_MARK":"prefix","BLACKLIST":"[]","_LAST_UPDATE_TIME":"0","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","THRESHOLD":"20","TRIM_WIDTH":"on","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","CLOUD_SYNC":"off","WHITELIST":"[]","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"60","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"0"}

**Tabs:**

- ID=1246438131 status=complete `https://www.bilibili.com/`

- ID=1246438178 status=complete `https://www.bilibili.com/video/BV1yr4y1Z7m1/?spm_id_from=333.851.b_7265636f6d6d656e64.2&vd_source=f77f7d88e700497cad62d65c11e55b1d`

- ID=1246438181 status=complete `undefined`

- ID=1246438184 status=loading `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

**Comment by xmcp** [comment] 2023-08-21 17:28
请更新到v10.2.7，但很可惜edge的审核仙人还在努力审核，预计需要一周时间。在此之前可以改为[从chrome web store安装](https://chrome.google.com/webstore/detail/pakku%EF%BC%9A%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%BC%B9%E5%B9%95%E8%BF%87%E6%BB%A4%E5%99%A8/jklfcpboamajpiikgkbjcnnnnooefbhh)。

duplicate of #250

**Closed by xmcp** 2023-08-21 17:28 UTC
