### ISSUE TITLE
加载不出6分钟以后的弹幕

### ISSUE THREAD

**Issue by Vicious-circIe** [xmcp/pakku.js#207] opened 2022-03-25 15:27 UTC
**是否可以稳定复现：**

基本稳定复现，偶尔能恢复正常，但出现概率极大

**复现步骤：**

1. 只要启用这个扩展无论打开哪个视频都会出现
2. 

**预期行为：**

加载显示完整弹幕列表

**实际行为：**

只加载了前6分钟的弹幕

**系统环境：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.1.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"off","TOOLTIP_KEYBINDING":"off","TAOLUS":"","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1648221442782","FLASH_NOTIF":"on","_ADVANCED_USER":"on","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"3","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"85","REMOVE_SEEK":"off","POPUP_BADGE":"percent","WHITELIST":"[]","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"on","PROC_TYPE7":"off","THRESHOLD":"3","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"off","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"off","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"0"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Permissions:** `{"origins":["*://*.bilibili.com/*","*://bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=328 status=complete `https://www.bilibili.com/`

- ID=423 status=complete `https://search.bilibili.com/all?keyword=%E8%A7%86%E9%A2%91%E5%88%B6%E4%BD%9C%E6%B5%81%E7%A8%8B&order=click&duration=0&tids_1=0&page=3`

- ID=426 status=complete `https://www.bilibili.com/video/BV1y44y1q7jH`

- ID=46 status=complete `https://www.bilibili.com/video/online.html`

- ID=439 status=unloaded `https://www.bilibili.com/judgement/index`

- ID=354 status=complete `https://t.bilibili.com/?tab=268435455`

- ID=292 status=unloaded `https://t.bilibili.com/626407292069124989`

- ID=52 status=unloaded `undefined`

- ID=281 status=unloaded `undefined`

- ID=314 status=complete `https://space.bilibili.com/393396916/dynamic`

- ID=272 status=complete `https://www.bilibili.com/video/BV1hb4y1q7eE?p=2`

- ID=384 status=complete `https://www.bilibili.com/read/cv14504611`

- ID=478 status=complete `undefined`

- ID=483 status=complete `undefined`

- ID=486 status=loading `undefined`

- ID=56 status=complete `https://space.bilibili.com/483162496/channel/seriesdetail?sid=292491`

- ID=295 status=unloaded `undefined`

- ID=298 status=unloaded `undefined`

- ID=302 status=unloaded `undefined`

- ID=305 status=unloaded `undefined`

- ID=308 status=unloaded `undefined`

- ID=311 status=unloaded `undefined`

- ID=64 status=complete `undefined`

- ID=66 status=complete `undefined`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"on","DANMU_MARK":"off","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"85","MAX_DIST":"3","MODE_ELEVATION":"off","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"off","PROC_TYPE7":"off","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"0","SHRINK":"off","TAOLUS":"","THRESHOLD":"3","TOOLTIP":"on","TOOLTIP_KEYBINDING":"off","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1648221442782"}

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,11">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">Ocarina的声音好奇怪</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,11">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">Ocarina的声音好奇怪</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

**Comment by olduck** [comment] 2022-03-31 18:08
+1，而且显示“该页面没有B站播放器”

**Comment by u2shana** [comment] 2022-04-01 12:23
我也是,6分钟后没弹幕加载

**Comment by xmcp** [comment] 2022-04-07 08:05
duplicate of #206

**Closed by xmcp** 2022-04-07 08:05 UTC
