### ISSUE TITLE
查询弹幕发送者的功能失效

### ISSUE THREAD

**Issue by hardshells** [xmcp/pakku.js#269] opened 2024-03-01 07:44 UTC
**是否可以稳定复现：**

稳定出现

**复现步骤：**

1. Ctrl选中弹幕后弹幕发送者弹不出来

**预期行为：**

同上

**实际行为：**

同上

**禁用pakku后bug是否存在：**

同上

**禁用其他插件后bug是否存在：**

和篡改猴插件同时开启会导致这个问题

**B站播放器版本号：**

4.8.4-c4539af2

**pakku调试信息：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.9

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"on","DANMU_MARK":"prefix","TAOLUS":"","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1692287114967","FLASH_NOTIF":"on","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","REMOVE_SEEK":"off","THRESHOLD":"20","POPUP_BADGE":"percent","TRIM_WIDTH":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"off","WHITELIST":"[]","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"60","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"1451138360":{"identical":42,"edit_distance":58,"pinyin_distance":1,"cosine_distance":64,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":9,"shrink":"","scroll":0,"taolu":5,"total":412,"onscreen":247,"maxcombo":30,"maxdispval":117.11370865567581,"error":null,"cid":"1454381094","parse_time_ms":13},"1451138447":{"identical":4,"edit_distance":15,"pinyin_distance":0,"cosine_distance":2,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":1,"shrink":"","scroll":0,"taolu":3,"total":379,"onscreen":358,"maxcombo":8,"maxdispval":51.36916985127034,"error":null,"cid":"1455012243","parse_time_ms":10}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","TAOLUS":"","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1692287114967"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=1451138360 status=complete `https://www.bilibili.com/`

- ID=1451138450 status=complete `https://www.bilibili.com/video/BV1qz421X7HZ/?spm_id_from=333.1007.tianma.1-1-1.click&vd_source=eb75180d93670e35e62ceda06316c1dd`

- ID=1451138447 status=complete `https://www.bilibili.com/video/BV1cK421h7T9/?spm_id_from=333.1007.tianma.2-2-5.click&vd_source=eb75180d93670e35e62ceda06316c1dd`

- ID=1451138453 status=complete `undefined`

- ID=1451138456 status=loading `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

应该和篡改猴有关，但是我并没有启动B站页面的任何脚本

**Comment by hardshells** [comment] 2024-03-01 07:48
和篡改猴疑似无关，现在关闭篡改猴功能依旧不正常

**Comment by hardshells** [comment] 2024-03-01 07:59
和网络疑似相关，更换网络之后功能正常了一个视频，刷新以及打开别的视频后功能任然不正常

**Comment by xmcp** [comment] 2024-03-01 09:49
duplicate of #264
注册时间比较新的用户（UID很长）确实查不出来。目前只能查询老用户（UID不超过十位）。

**Closed by xmcp** 2024-03-01 09:49 UTC
